#!/usr/bin/env zsh

DOTFILES=${0:A:h}

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.local/bin

rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.local/bin/kitty-toggle
ln -s $DOTFILES/scripts/kitty-toggle $HOME/.local/bin/kitty-toggle

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim-personal $HOME/.config/nvim
